---
services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    network_mode: host # This makes IPv6 easier; see below
    restart: always
    user: "1000:1000" # Run the updater with specific user and group IDs
    cap_drop: [all] # Drop all other capabilities
    read_only: true # Make the container filesystem read-only
    security_opt: [no-new-privileges:true] # Another protection to restrict superuser privileges
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN} # Your Cloudflare API token
      - DOMAINS=korps.dev # Your domains (separated by commas)
      - PROXIED=true # Tell Cloudflare to cache webpages and hide your IP
    env_file: .env