services:
  myspeed:
    image: germannewsmaker/myspeed:1.0.9
    container_name: MySpeed
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
        - 5216:5216
    volumes:
        - /docker/services/myspeed:/myspeed/data

networks:
  reverse_proxy:
    external: true