---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.7.1
    container_name: mealie
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
        - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /docker/services/mealie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=false
      - PUID=1000
      - PGID=10000
      - TZ=America/Los_Angeles
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.korps.dev

networks:
 reverse_proxy:
   external: true