services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.30.0
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
      - 8085:80
    volumes:
      - /nas:/srv
      - /docker/services/filebrowser/filebrowser.db:/database/filebrowser.db
      - /docker/services/filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=10000

networks:
 reverse_proxy:
   external: true