services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2.27.0
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - 8085:80
    volumes:
      - /mnt/storage/nas:/srv
      - /mnt/storage/services/filebrowser/filebrowser.db:/database/filebrowser.db
      - /mnt/storage/services/filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=10000
    labels:
      - "traefik.enable=true"
      # HTTP      
      - "traefik.http.routers.filebrowser.entrypoints=http"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.korps.dev`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.filebrowser.middlewares=https-redirect"
      # HTTPS
      - "traefik.http.routers.filebrowser-secure.rule=Host(`filebrowser.korps.dev`)"
      - "traefik.http.routers.filebrowser-secure.entrypoints=https"
      - "traefik.http.routers.filebrowser-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.filebrowser-secure.tls=true"


networks:
 traefik_proxy:
   external: true