services:
  actual_server:
    image: docker.io/actualbudget/actual-server:25.1.0
    container_name: actual
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
      - '5006:5006'
    volumes:
      - /docker/services/actual:/data
    environment:
      - ACTUAL_TRUSTED_PROXIES=192.168.0.0/16
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration

networks:
 reverse_proxy:
   external: true