services:
  actual_server:
    image: docker.io/actualbudget/actual-server:24.12.0
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - '5006:5006'
    volumes:
      - /docker/services/actual:/data
    environment:
      - ACTUAL_TRUSTED_PROXIES=192.168.0.0/16
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.actual.rule=Host(`actual.korps.dev`)"
      - "traefik.http.routers.actual.entrypoints=http"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.actual.middlewares=https-redirect"
      # https
      - "traefik.http.routers.actual-secure.rule=Host(`actual.korps.dev`)"
      - "traefik.http.routers.actual-secure.entrypoints=https"
      - "traefik.http.routers.actual-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.actual-secure.loadbalancer.server.port=5006"

networks:
 traefik_proxy:
   external: true