services:
  gitea-app:
    image: gitea/gitea:1.21.8-rootless
    restart: always
    networks:
      - traefik_proxy
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - gitea-db
    volumes:
      - /mnt/storage/services/gitea/data:/var/lib/gitea
      - /mnt/storage/services/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-db:5432
      - GITEA__database__NAME= # database
      - GITEA__database__USER= # user
      - GITEA__database__PASSWD= # password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.korps.dev`)"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.tls.certresolver=cloudflare"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

  gitea-db:
    image: postgres:14
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - /mnt/storage/services/gitea/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER= # user
      - POSTGRES_PASSWORD= # password
      - POSTGRES_DB= # database

  # gitea-runner:
  #   image: gitea/act_runner:latest
  #   restart: always
  #   networks:
  #     - traefik_proxy
  #   depends_on:
  #     - gitea-app
  #   volumes:
  #     - /mnt/storage/services/gitea/act_runner:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - GITEA_INSTANCE_URL=gitea.korps.dev
  #     # When using Docker Secrets, it's also possible to use
  #     # GITEA_RUNNER_REGISTRATION_TOKEN_FILE to pass the location.
  #     # The env var takes precedence.
  #     # Needed only for the first start.
  #     - GITEA_RUNNER_REGISTRATION_TOKEN=

networks:
 traefik_proxy:
   external: true