# https://hub.docker.com/r/pihole/pihole/tags
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.05.0
    restart: unless-stopped
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      # WEBPASSWORD: 'set a secure password here or it will be random'
      PIHOLE_DNS_: '1.1.1.1;1.0.0.1'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'