# https://hub.docker.com/r/linuxserver/code-server/tags
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.21.0
    container_name: code-server
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=${PASSWORD}
      - PROXY_DOMAIN=codeserver.korps.dev
      - DEFAULT_WORKSPACE=/config/services #optional
    env_file: .env
    volumes:
      - /mnt/storage/services:/config
      - ../:/config/services
    ports:
      - 8443:8443/tcp # Web UI
    labels:
      - traefik.enable=true
      - traefik.http.routers.codeserver.rule=Host(`codeserver.korps.dev`)
      - traefik.http.routers.codeserver.entrypoints=https
      - traefik.http.routers.codeserver.tls.certresolver=cloudflare

networks:
  traefik_proxy:
    external: true
