---
# Thanks Jeff - https://www.jeffgeerling.com/blog/2022/ansible-playbook-upgrade-ubuntudebian-servers-and-reboot-if-needed
- hosts: nas.lan
  gather_facts: yes
  remote_user: root
  tasks:
  
    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install Samba
      ansible.builtin.apt:
        name: samba
        state: present
    
    - name: Set up LXC Share for pve bind mount
      ansible.builtin.group:
        name: lxcshare
        state: present
        gid: 10000
    
    - name: Add default user with 'sudo'
      ansible.builtin.user:
        name: will
        uid: 1000
        groups: sudo, sambashare, lxcshare
        shell: /bin/bash
        createhome: yes
        # password: '' # ⚠️ Package: whois | Run: $ mkpasswd --method=sha-512

    - name: Add Public Samba User
      ansible.builtin.user:
        name: cookie
        uid: 1001
        groups: sambashare, lxcshare
        createhome: no
        # password: '' # ⚠️ Package: whois | Run: $ mkpasswd --method=sha-512

    - name: Check For Existing Samba Configuration File
      ansible.builtin.stat: 
        path: /etc/samba/smb.conf
      register: conf

    - name: Back up Samba Configuration File
      command: mv /etc/samba/smb.conf /etc/samba/smb.conf.bak
      when: conf.stat.exists

    - name: Get Samba Config 
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/Wcarcamo/self-hosted/main/ansible/config_files/smb.conf
        dest: /etc/samba/smb.conf
        mode: '0440'

    - name: Reload smbd service
      ansible.builtin.systemd_service:
        name: smbd
        state: reloaded

    - name: Print message
      ansible.builtin.debug:
        msg: 'Manually set smb passwords "sudo smbpasswd -a username"'