- hosts: dev
  # become: yes
  remote_user: root
  tasks:

    - name: install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        update_cache: yes

    - name: add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      
    - name: get ubuntu version
      command: "lsb_release -cs"
      register: ubuntu_version

    - name: add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present

    - name: update apt cache
      apt:
        update_cache: yes

    - name: install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        update_cache: yes

    - name: Add default user with 'sudo'
      ansible.builtin.user:
        name: will
        uid: 1000
        groups: sudo, docker
        shell: /bin/bash
        createhome: yes
        # Package: whois | Run: $ mkpasswd --method=sha-512
        password: ''
 