- hosts: docker.lan
  remote_user: root
  tasks:

    - name: install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - git
          - gpg
        update_cache: yes

    - name: add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      
    - name: get ubuntu version
      command: "lsb_release -cs"
      register: ubuntu_version

    - name: add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present

    - name: update apt cache
      apt:
        update_cache: yes

    - name: install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        update_cache: yes

    - name: Set up LXC Share for pve bind mount
      ansible.builtin.group:
        name: lxcshare
        state: present
        gid: 10000

    - name: Add default user with 'sudo' & 'docker' user
      ansible.builtin.user:
        name: will
        uid: 1000
        groups: sudo, docker, lxcshare
        shell: /bin/bash
        createhome: yes
        # password: '' # ⚠️ Package: whois | Run: $ mkpasswd --method=sha-512
 