---
- hosts: proxmox.lan
  gather_facts: yes
  remote_user: root
  tasks:
  
    - name: Install mergerfs
      ansible.builtin.apt:
        deb: https://github.com/trapexit/mergerfs/releases/download/2.40.2/mergerfs_2.40.2.debian-bookworm_amd64.deb

    - name: Set Up mergerfs pool
      ansible.builtin.file:
        path: /mnt/storage
        state: directory

    - name: Mount mergerfs pool
      ansible.posix.mount:
        src: /disk*
        path: /mnt/storage
        fstype: fuse.mergerfs
        opts: defaults,nonempty,allow_other,use_ino,cache.files=off,moveonenospc=true,dropcacheonclose=true,minfreespace=16G,fsname=mergerfs
        state: mounted

    - name: Fix Pool Permissions
      ansible.builtin.file:
        path: /mnt/storage
        state: directory
        owner: 101000
        group: 110000
        mode: '2777'