services:
  homer:
    image: b4bz/homer:v24.11.5
    container_name: homer
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
      - 8090:8080
    volumes:
      - ./data/:/www/assets

networks:
  reverse_proxy:
    external: true