services:
  healthchecks-db:
    image: postgres:12
    volumes:
      - /mnt/storage/services/healthchecks:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
  healthchecks-app:
    image: healthchecks/healthchecks:latest
    ports:
        - "8000:8000"
        # To enable SMTP on port 2525, set SMTPD_PORT=2525 in .env
        # and uncomment the following line:
        # - "2525:2525"
    depends_on:
        - db
    env_file:
        - .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'