---
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      - reverse_proxy
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=America/Los_Angeles
    volumes:
      - /docker/services/nginx:/config
    ports:
      - 8082:80
      - 8449:443

networks:
  reverse_proxy:
    external: true