services:
    vikunja:
      image: vikunja/vikunja
      container_name: vikunja
      restart: unless-stopped
      networks:
        - reverse_proxy
      ports:
          - 3456:3456
      volumes:
          - /docker/services/vikunja/app:/app/vikunja/files
      env_file:
        - .env
      environment:
          # VIKUNJA_SERVICE_PUBLICURL: http://todo.korps.dev
          VIKUNJA_DATABASE_TYPE: postgres
          VIKUNJA_DATABASE_HOST: vikunja_db
          VIKUNJA_DATABASE_PASSWORD: ${VIKUNJA_DATABASE_PASSWORD}
          VIKUNJA_DATABASE_USER: vikunja
          VIKUNJA_DATABASE_DATABASE: vikunja
          VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      depends_on:
          vikunja_db:
              condition: service_healthy
    vikunja_db:
      image: postgres:16
      container_name: vikunja_db
      networks:
        - reverse_proxy
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: vikunja
      volumes:
        - /docker/services/vikunja/db:/var/lib/postgresql/data
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER"]
        interval: 2s

networks:
  reverse_proxy:
    external: true