services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.23
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - 8083:8083
    volumes:
      - /docker/services/calibre:/config
      - /nas/books/calibre:/books
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=America/Los_Angeles
      # - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    labels:
      - traefik.enable=true
      - traefik.http.routers.calibre.rule=Host(`calibre.korps.dev`)
      - traefik.http.routers.calibre.entrypoints=https
      - traefik.http.routers.calibre.tls.certresolver=cloudflare

networks:
  traefik_proxy:
    external: true