services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.23
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - reverse_proxy
    ports:
      - 8083:8083
    volumes:
      - /docker/services/calibre:/config
      - /nas/books/calibre:/books
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=America/Los_Angeles
      # - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional

networks:
  reverse_proxy:
    external: true