services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    networks:
      - traefik_proxy
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    labels:
      - "traefik.enable=true"
      # # http
      - "traefik.http.routers.wud.rule=Host(`wud.korps.dev`)"
      - "traefik.http.routers.wud.entrypoints=http"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wud.middlewares=https-redirect"
      # https
      - "traefik.http.routers.wud-secure.rule=Host(`wud.korps.dev`)"
      - "traefik.http.routers.wud-secure.entrypoints=https"
      - "traefik.http.routers.wud-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.wud-secure.loadbalancer.server.port=3000"

networks:
 traefik_proxy:
   external: true