---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.13
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - 8096:8096
      - 8920:8920 #optional - set up reverse proxy with
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    volumes:
      - /mnt/storage/services/jellyfin:/config
      - /mnt/storage/tvshows:/data/tvshows
      - /mnt/storage/movies:/data/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      # - JELLYFIN_PublishedServerUrl=jellyfin.korps.dev #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.korps.dev`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls.certresolver=cloudflare"

networks:
  traefik_proxy:
    external: true