services:
  freshrss:
    # https://hub.docker.com/r/freshrss/freshrss
    image: lscr.io/linuxserver/freshrss:1.25.0
    container_name: freshrss
    restart: unless-stopped
    networks:
      - reverse_proxy
    volumes:
      - /docker/services/freshrss:/config
    ports:
      - 8132:80
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=10000

networks:
 reverse_proxy:
   external: true