---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.1.1
    container_name: mealie-v1
    restart: always
    networks:
      - traefik_proxy
    ports:
        - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /mnt/storage/services/mealie:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=10000
      - TZ=America/Los_Angeles
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.korps.dev
    labels:
      - "traefik.enable=true"
      # HTTP      
      - "traefik.http.routers.mealie.entrypoints=http"
      - "traefik.http.routers.mealie.rule=Host(`mealie.korps.dev`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mealie.middlewares=https-redirect"
      # HTTPS
      - "traefik.http.routers.mealie-secure.entrypoints=https"
      - "traefik.http.routers.mealie-secure.rule=Host(`mealie.korps.dev`)"
      - "traefik.http.routers.mealie-secure.tls=true"
      - "traefik.http.routers.mealie-secure.tls.certresolver=cloudflare"

networks:
 traefik_proxy:
   external: true